## TODO: using an old version of zprezto because lfilho was, probably ok to update.
#[".zprezto"]
#    type = "archive"
#    url = "https://github.com/sorin-ionescu/prezto/archive/1f4601e44c989b90dc7314b151891fa60a101251.tar.gz"
#    exact = true
#    stripComponents = 1

# [".emacs.d"]
#     type = "archive"
#     url = "https://github.com/hlissner/doom-emacs/archive/develop.tar.gz"
#     exact = true
#     stripComponents = 1
#     refreshPeriod = "168h"
[".zsh/fzf-git.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/fzf-git.sh/main/fzf-git.sh"
    refreshPeriod = "168h"
[".emacs.d"]
  type = "git-repo"
  #url = "https://github.com/hlissner/doom-emacs"
  url = "https://github.com/doomemacs/doomemacs"
[".setup"]
  type = "git-repo"
  url = "https://github.com/coreyjewett/nix-config.git"
