#!/bin/bash
set -eio pipefail

haz() { command -v "$1" &> /dev/null; }
darwin() { test "$(uname)" = "Darwin"  }
linux() { test "$(uname)" = "Linux"  }

# Try to load linuxbrew, or install brew
test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
if ! haz brew; then
    /bin/bash -c "export CI=1; $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
fi

# install Brewfilw goodness
brew bundle install --file=~/.Brewfile
brew bundle install --file=~/.Brewfile.$(uname)

# ijq
if ! haz ijq; then
    IJQ_VER=0.3.6
    TMPDIR=$(mktemp -d)
    pushd $TMPDIR
    curl -L https://github.com/gpanders/ijq/archive/refs/tags/v${IJQ_VER}.tar.gz | tar xz
    cd ijq-${IJQ_VER}
    sudo make install
    popd
    rm -rf $TMPDIR
fi
