#!/bin/bash
set -eio pipefail

CHEZMOI_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $CHEZMOI_ROOT

haz() { command -v "$1" &> /dev/null; }
darwin() { test "$(uname)" = "Darwin";  }
linux() { test "$(uname)" = "Linux"; }

export PATH=~/.bin:$PATH

# Correct Chezmoi repo to ssh version
chezmoi git remote set-url origin git@github.com:coreyjewett/dotfiles.git

# Try to load linuxbrew, or install brew
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
if ! haz brew; then
    /bin/bash -c "export CI=1; $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
fi

# install Brewfile goodness
brew bundle install --file=~/.Brewfile

# seems like there may be a catch-22 here
touch ~/.zsh_history

# ijq
if ! haz ijq; then
    IJQ_VER=0.3.6
    TMPDIR=$(mktemp -d)
    pushd $TMPDIR
    curl -L https://github.com/gpanders/ijq/archive/refs/tags/v${IJQ_VER}.tar.gz | tar xz
    cd ijq-${IJQ_VER}
    make
    sudo make install
    popd
    rm -rf $TMPDIR
fi
