#!/usr/bin/env lua

-- For LUA to actually find the module, it has to reside in a path included in the lua cpath (https://github.com/FelixKratz/SbarLua#lua-module)
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

-- https://github.com/FelixKratz/dotfiles/issues/64#issuecomment-2452804290
package.path = "./?.lua;./?/init.lua;" .. package.path

-- Load the sketchybar-package and prepare the helper binaries
require("helpers")
require("init")
